image:
  repository: cueverz/devops-backend
  tag: "01"

service:
  type: NodePort
  port: 8000

mysql:
  host: my-mysql.default.svc.cluster.local
  database: flaskreact
  user: helmdb
  password: Team1234#


